#!/usr/bin/env python3
"""Turn data/*.yml into the bits of the site that display personal details.

Run automatically by Quarto as a `pre-render` step (see _quarto.yml); run it by
hand with `python3 _render/build.py` if you want to inspect the output.

Writes two things, both gitignored because both are derived:

  _variables.yml      scalars for inline use in prose, e.g. {{< var personal.name >}}
  _generated/*.md     markdown partials for the repeating lists, pulled into
                      pages with {{< include _generated/cv-education.md >}}

The point of the arrangement: no .qmd file contains a name, date, job title or
affiliation. data/cv.yml is the only place any of that lives.
"""

from __future__ import annotations

import sys
from datetime import date, datetime
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover - environment guard
    sys.exit(
        "build.py needs PyYAML. Install it with:  python3 -m pip install pyyaml"
    )

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
GENERATED = ROOT / "_generated"

EN_DASH = "–"


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------

def read_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def deep_merge(base: dict, overlay: dict) -> dict:
    """Overlay wins. Nested dicts merge; lists and scalars are replaced."""
    out = dict(base)
    for key, value in overlay.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def load_cv() -> dict:
    """data/cv.yml, with data/cv.private.yml layered on top if it exists."""
    cv = read_yaml(DATA / "cv.yml")
    private = read_yaml(DATA / "cv.private.yml")
    return deep_merge(cv, private) if private else cv


# --------------------------------------------------------------------------
# formatting helpers
# --------------------------------------------------------------------------

def as_text(value) -> str:
    """YAML may hand us dates or numbers; markdown wants strings."""
    if value is None:
        return ""
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    return str(value).strip()


def date_range(start, end) -> str:
    """'2024 – Present', '2023 – 2024', or a lone date."""
    start, end = as_text(start), as_text(end)
    if start and end:
        return f"{start} {EN_DASH} {end}"
    if start:
        return f"{start} {EN_DASH} Present"
    return end


def pretty_date(value) -> str:
    """ISO dates become '14 June 2025'; anything else passes through."""
    text = as_text(value)
    for fmt in ("%Y-%m-%d", "%Y-%m"):
        try:
            parsed = datetime.strptime(text, fmt)
        except ValueError:
            continue
        return parsed.strftime("%B %Y" if fmt == "%Y-%m" else "%-d %B %Y")
    return text


def sort_key(value) -> str:
    """Sort talks newest-first without choking on non-ISO dates."""
    return as_text(value)


def entry_block(dates: str, heading: str, subheading: str, notes: str) -> str:
    """One two-column CV row. Styling lives in styles.scss."""
    lines = ["::: {.cv-entry}", f"::: {{.cv-dates}}\n{dates or '&nbsp;'}\n:::", "::: {.cv-body}"]
    head = f"**{heading}**" if heading else ""
    if subheading:
        head = f"{head} <span class='cv-org'>{subheading}</span>" if head else subheading
    if head:
        lines.append(head)
    if notes:
        lines.append("")
        lines.append(f"::: {{.cv-notes}}\n{notes}\n:::")
    lines.append(":::")
    lines.append(":::")
    return "\n".join(lines)


def placeholder(what: str) -> str:
    return (
        f"::: {{.callout-note appearance='minimal'}}\n"
        f"No {what} yet — add entries to `data/cv.yml`.\n"
        f":::"
    )


HEADER = "<!-- Generated by _render/build.py from data/*.yml. Do not edit. -->\n"


def write(name: str, body: str) -> None:
    GENERATED.mkdir(exist_ok=True)
    (GENERATED / name).write_text(HEADER + body.rstrip() + "\n", encoding="utf-8")


# --------------------------------------------------------------------------
# section builders
# --------------------------------------------------------------------------

def build_education(cv: dict) -> None:
    entries = cv.get("education") or []
    blocks = [
        entry_block(
            date_range(e.get("start"), e.get("end")),
            as_text(e.get("qualification")),
            as_text(e.get("institution")),
            as_text(e.get("notes")),
        )
        for e in entries
    ]
    write("cv-education.md", "\n\n".join(blocks) if blocks else placeholder("education"))


def build_roles(cv: dict) -> None:
    entries = cv.get("roles") or []
    blocks = [
        entry_block(
            date_range(e.get("start"), e.get("end")),
            as_text(e.get("title")),
            as_text(e.get("organisation")),
            as_text(e.get("notes")),
        )
        for e in entries
    ]
    write("cv-roles.md", "\n\n".join(blocks) if blocks else placeholder("roles"))


def build_awards(cv: dict) -> None:
    entries = cv.get("awards") or []
    blocks = [
        entry_block(
            as_text(e.get("year")),
            as_text(e.get("title")),
            as_text(e.get("awarder")),
            as_text(e.get("notes")),
        )
        for e in entries
    ]
    write("cv-awards.md", "\n\n".join(blocks) if blocks else placeholder("awards"))


def build_skills(cv: dict) -> None:
    groups = cv.get("skills") or []
    blocks = []
    for group in groups:
        items = ", ".join(as_text(i) for i in (group.get("items") or []) if as_text(i))
        blocks.append(entry_block(as_text(group.get("category")), "", "", items))
    write("cv-skills.md", "\n\n".join(blocks) if blocks else placeholder("skills"))


def build_contact(cv: dict) -> None:
    """Link row used on the About page."""
    links = (cv.get("personal") or {}).get("links") or []
    rendered = [
        f"[{as_text(l.get('label'))}]({as_text(l.get('url'))})"
        for l in links
        if as_text(l.get("label")) and as_text(l.get("url"))
    ]
    body = (
        "::: {.profile-links}\n" + " · ".join(rendered) + "\n:::"
        if rendered
        else "<!-- no links in data/cv.yml -->"
    )
    write("contact-links.md", body)


def build_talks() -> None:
    talks = (read_yaml(DATA / "talks.yml") or {}).get("talks") or []
    talks = sorted(talks, key=lambda t: sort_key(t.get("date")), reverse=True)

    blocks = []
    for talk in talks:
        title = as_text(talk.get("title"))
        venue = as_text(talk.get("venue"))
        slides = as_text(talk.get("slides_url"))
        notes = venue
        if slides:
            notes = f"{notes}<br>[Slides]({slides})" if notes else f"[Slides]({slides})"
        blocks.append(entry_block(pretty_date(talk.get("date")), title, "", notes))

    write(
        "talks.md",
        "\n\n".join(blocks)
        if blocks
        else "::: {.callout-note appearance='minimal'}\nNo talks yet — add entries to `data/talks.yml`.\n:::",
    )


def build_variables(cv: dict) -> None:
    """Scalars for {{< var ... >}} in page prose."""
    personal = cv.get("personal") or {}
    variables = {
        "personal": {
            key: as_text(personal.get(key))
            for key in ("name", "role", "affiliation", "tagline", "email", "location")
        }
    }
    with (ROOT / "_variables.yml").open("w", encoding="utf-8") as fh:
        fh.write("# Generated by _render/build.py from data/cv.yml. Do not edit.\n")
        yaml.safe_dump(variables, fh, allow_unicode=True, sort_keys=False)


def main() -> None:
    cv = load_cv()
    if not cv:
        sys.exit(f"No CV data found — expected {DATA / 'cv.yml'}")

    build_variables(cv)
    build_education(cv)
    build_roles(cv)
    build_awards(cv)
    build_skills(cv)
    build_contact(cv)
    build_talks()

    print(f"build.py: wrote _variables.yml and {len(list(GENERATED.glob('*.md')))} partials")


if __name__ == "__main__":
    main()
